apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: nginx
          ports:
          - containerPort: 80