apiVersion : apps/v1
kind: Deployment
metadata:
  name: website 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website 
    spec:
      containers:
        - name: guywizards/test-website 
          image: nginx
          ports:
          - containerPort: 80